name = "truepulse"
main = "src/index.js"
compatibility_date = "2025-08-14"

# Ensure the worker only applies to subdomains
routes = [
  { pattern = "*.truepulse.io/*", zone_name = "truepulse.io" }
]

# Optional (for logging or custom env)
logpush = false
